# Generated by Django 3.1 on 2020-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinstance',
            name='id_docuement',
            field=models.IntegerField(blank=True, help_text='Уникальный ID', null=True, verbose_name='Уникальный ID'),
        ),
    ]
