# Generated by Django 3.1 on 2020-11-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderinstance_id_docuement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinstance',
            old_name='id_docuement',
            new_name='id_document',
        ),
    ]
