# Generated by Django 3.1 on 2020-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201130_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinstance',
            name='id_document',
            field=models.IntegerField(blank=True, default=0, help_text='Уникальный ID', verbose_name='Уникальный ID'),
        ),
    ]
