# Generated by Django 3.0.8 on 2021-01-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201130_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinstance',
            options={'ordering': ['-due_back', '-status'], 'permissions': (('sign_order', 'Can sign order'),), 'verbose_name': 'Распоряжение', 'verbose_name_plural': 'Распоряжения'},
        ),
    ]
