# Generated by Django 3.1 on 2020-11-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_accept',
            field=models.CharField(default='Исполнено', help_text='Подпись согласования', max_length=120, verbose_name='Согласования'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_disaccept',
            field=models.CharField(default='Отказано', help_text='Подпись отказа', max_length=120, verbose_name='Отказ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_in_working',
            field=models.CharField(default='На исполнении', help_text='Подпись в процессе', max_length=120, verbose_name='Процесс'),
        ),
    ]
