# Generated by Django 3.1 on 2020-11-16 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Адрес отправки', max_length=120, verbose_name='Адрес отправки')),
            ],
            options={
                'verbose_name': 'Адрес отправки',
                'verbose_name_plural': 'Адреса отправки',
            },
        ),
        migrations.CreateModel(
            name='Attechment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attechment', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Вложение ЖД документа',
                'verbose_name_plural': 'Вложения ЖД документов',
            },
        ),
        migrations.CreateModel(
            name='RailwayOrder',
            fields=[
                ('date_of_shipment', models.DateField(verbose_name='Дата')),
                ('date_of_created', models.DateField(verbose_name='Дата создания')),
                ('note', models.TextField(blank=True, help_text='Комментарий', max_length=324, verbose_name='Комментарий')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Номер документа')),
                ('type_railwayorder', models.CharField(blank=True, choices=[('s', 'Отправка'), ('r', 'Приемка')], default='r', max_length=16, verbose_name='Тип документа')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rw_address', to='railwayplatform.address', verbose_name='Адрес отправки')),
                ('attechment', models.ManyToManyField(blank=True, related_name='attechment_rworder', to='railwayplatform.Attechment', verbose_name='Вложения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rw_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор документа')),
            ],
            options={
                'verbose_name': 'ЖД документ',
                'verbose_name_plural': 'ЖД документы',
                'ordering': ['-date_of_created'],
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ф.И.О. или Название', max_length=86, verbose_name='Ф.И.О. или Название')),
            ],
            options={
                'verbose_name': 'Груза отправитель',
                'verbose_name_plural': 'Груза отправители',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ф.И.О. или Название', max_length=86, verbose_name='Ф.И.О. или Название')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SenderDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_wagon', models.IntegerField(help_text='Количество вагонов', verbose_name='Количество вагонов')),
                ('sender_gross', models.DecimalField(decimal_places=2, help_text='Брутто', max_digits=11, verbose_name='Брутто')),
                ('sender_tara', models.DecimalField(decimal_places=2, help_text='Тара', max_digits=11, verbose_name='Тара')),
                ('sender_net', models.DecimalField(decimal_places=2, help_text='Нетто', max_digits=11, verbose_name='Нетто')),
                ('note', models.TextField(blank=True, help_text='Прочие', max_length=160, verbose_name='Прочие')),
                ('rworder_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderdoc_rworder', to='railwayplatform.railwayorder', verbose_name='ЖД Заявка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sendoc', to='railwayplatform.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Убывший вагон',
                'verbose_name_plural': 'Убывшие вагоны',
            },
        ),
        migrations.CreateModel(
            name='RecipientDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_wagon', models.IntegerField(help_text='Количество вагонов', verbose_name='Количество вагонов')),
                ('sender_gross', models.DecimalField(decimal_places=2, help_text='Брутто', max_digits=11, verbose_name='Брутто')),
                ('sender_tara', models.DecimalField(decimal_places=2, help_text='Тара', max_digits=11, verbose_name='Тара')),
                ('sender_net', models.DecimalField(decimal_places=2, help_text='Нетто', max_digits=11, verbose_name='Нетто')),
                ('rec_gross', models.DecimalField(decimal_places=2, help_text='Брутто', max_digits=11, verbose_name='Брутто')),
                ('rec_tara', models.DecimalField(decimal_places=2, help_text='Тара', max_digits=11, verbose_name='Тара')),
                ('rec_net', models.DecimalField(decimal_places=2, help_text='Нетто', max_digits=11, verbose_name='Нетто')),
                ('difference', models.DecimalField(decimal_places=2, help_text='Разница', max_digits=11, verbose_name='Разница')),
                ('note', models.TextField(blank=True, help_text='Прочие', max_length=160, verbose_name='Прочие')),
                ('rworder_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipientdoc_rworder', to='railwayplatform.railwayorder', verbose_name='ЖД Заявка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rcdoc', to='railwayplatform.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Прибывший вагон',
                'verbose_name_plural': 'Прибывшие вагоны',
            },
        ),
        migrations.AddField(
            model_name='railwayorder',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_rworder', to='railwayplatform.shipper', verbose_name='Груза отправитель'),
        ),
    ]
