# Generated by Django 3.0.8 on 2021-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railwayplatform', '0008_auto_20201130_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwayorder',
            name='type_railwayorder',
            field=models.CharField(blank=True, choices=[('r', 'Прибыл'), ('p', 'Готовится к отправке'), ('s', 'В пути')], default='p', max_length=16, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='recipientdoc',
            name='number_of_wagon',
            field=models.IntegerField(help_text='Номер вагона', verbose_name='Номер вагона'),
        ),
        migrations.AlterField(
            model_name='senderdoc',
            name='number_of_wagon',
            field=models.IntegerField(help_text='Номер вагона', verbose_name='Номер вагона'),
        ),
    ]
